repo: null
host: null
cluster: null
customDomain: null
name: rollout-test
imageName: null
default:
  cpuLimit: 500m
  memoryLimit: 512Mi
  min: 1
  max: 10
  target: 50
  cluster: circuit-1
  host: getcircuit.io
  gateway: public
  repo: europe-west2-docker.pkg.dev/circuit-api-284012/getcircuit
  port: 8080
  version: latest
  namespace: apps
  public: true
  metricsInterval: 15s
  projectId: '649859665426'
rolloutStrategy:
- setWeight: 5
- pause: {}
environments:
- production: true
  metrics:
    enabled: true