repo: null
host: null
cluster: null
customDomain: null
name: null
imageName: null
default:
  cpuLimit: 500m
  memoryLimit: 512Mi
  min: 1
  max: 10
  target: 50
  cluster: circuit-1
  host: getcircuit.io
  gateway: public
  repo: europe-west2-docker.pkg.dev/circuit-api-284012/getcircuit
  port: 8080
  version: latest
  namespace: apps
  public: true
  metricsInterval: 30s
  projectId: '649859665426'
  healthcheck:
    liveness:
      path: /health
      delay: 20
      interval: 10
      failure: 3
      timeout: 30
      success: 1
    readiness:
      path: /health
      delay: 10
      interval: 10
      failure: 3
      timeout: 30
      success: 1
rolloutStrategy:
- setWeight: 5
- pause: {}
environments:
- production: true
  metrics:
    enabled: true
mirror:
  enabled: false
  percentage:
  environment: