name: service-template
environments:
- env:
    TEST_ENV: Example env var
    A_SECRET_VALUE: ${gcp:staging--secret--value/1}
    ANOTHER_SECRET_VALUE: ${gcp:very--secret/1}
  metrics:
    enabled: true
    interval: 10s
  minReplicas: 1
  maxReplicas: 5
  port: 3000
  production: true
  customDomains:
  - api.getcircuit.com
  - api-test.getcircuit.com
  customMatch:
  - uri:
      prefix: "/rest"
  - uri:
      prefix: "/health"
  version: v0.0.2
  targetCPU: 80
  public: true
  volumes:
    secrets:
    - name: firestore-service-accounts
      path: /etc/secrets
      items: 
        - key: "api.json"
          path: "api.json"
        - key: "consumer.json"
          path: "consumer.json"
        - key: "dev.json"
          path: "dev.json"
        - key: "teams.json"
          path: "teams.json"
        - key: "test.json"
          path: "test.json"
    - from: ${gcp:mounted--secret/1}
      path: /etc/secret
      file: 'asdf.json'
      name: mounted-secret
  rolloutAnalysis:
    successCondition: 0.99
  customRoute:
  - name: route-to-ms
    match:
    - uri:
        prefix: "/my-ms"
    route:
    - destination:
        host: my-ms
  healthcheck:
    enabled: true
    liveness:
      path: /health
      delay: 20
      interval: 10
      failure: 3
      timeout: 30
    readiness:
      path: /health
      delay: 10
      interval: 10
      failure: 3
      timeout: 30
      success: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits: 
      cpu: 1
      memory: 1Gi
- env:
    TEST_ENV: Staging env var
  metrics:
    enabled: true
    interval: 60s
  minReplicas: 1
  maxReplicas: 5
  port: 3000
  production: false
  name: staging
  command: ["my", "custom", "command"]
  version: v0.0.2
  targetCPU: 95
  public: true
  volumes:
    secrets:
    - name: firestore-service-accounts
      path: /etc/secrets
      items: 
        - key: "api.json"
          path: "api.json"
        - key: "consumer.json"
          path: "consumer.json"
        - key: "dev.json"
          path: "dev.json"
        - key: "teams.json"
          path: "teams.json"
        - key: "test.json"
          path: "test.json"
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits: 
      cpu: 500m
      memory: 256Mi
