{{- if not .Values.name }}
  {{ fail "You must provide a `service.name` in values.yaml" }}
{{- end }}
{{- /* */}}
{{ $repo := .Values.repo | default .Values.default.repo }}
{{ $namespace := .Values.namespace | default .Values.default.namespace }}
{{- /* */}}
{{ $seenProdBefore := 0 }}
{{- /* */}}
{{- range $k, $environment := .Values.environments }}
{{ $version := $environment.version | default $.Values.default.version }}
{{- /* */}}
{{- if not $environment.name }}
  {{- if not $environment.production }}
    {{ fail "You must provide a `service.environments[].name` for non-production environments in values.yaml" }}
  {{- end }}
{{- end }}
{{- /* */}}
{{ $cpuLimit := $.Values.default.cpuLimit }}
{{ $memoryLimit := $.Values.default.memoryLimit }}
{{- /* */}}
{{ $requestedCpu := "" }}
{{ $requestedMemory := "" }}
{{- /* */}}
{{- if $environment.resources }}
  {{- if $environment.resources.requests }}
  {{ $requestedMemory = $environment.resources.requests.memory }}
  {{ $requestedCpu = $environment.resources.requests.cpu }}
  {{- end }}
  {{- if $environment.resources.limits }}
    {{ $memoryLimit = $environment.resources.limits.memory }}
    {{ $cpuLimit = $environment.resources.limits.cpu }}
  {{- end }}
{{- end }}
{{- /* */}}
{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{- /* */}}
{{ if $environment.production }}
  {{ if $seenProdBefore }}
    {{ fail "You may only have ONE production environment" }}
  {{ else }}
  {{ $seenProdBefore = 1 }}
  {{- end }}
  {{ $name = $.Values.name }}
{{- end }}
{{- /* */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        circuit/service-name: {{ $.Values.name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ printf "%s/%s:%s" $repo $.Values.name $version }}
          ports:
          - name: http
            containerPort: {{ $environment.port | default $.Values.default.port }}
          imagePullPolicy: IfNotPresent
          resources: 
            {{- if $requestedCpu }}
            requests:
              memory: {{ $requestedCpu }}
              cpu: {{ $requestedMemory }}
            {{- end }}
            limits:
              memory: {{ $memoryLimit }}
              cpu: {{ $cpuLimit }}
          {{- if $environment.env }}
          {{- /* */}}
          env:
          {{- range $key, $value := $environment.env}}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- /* */}}
          {{- end }}
      {{- if or $environment.secret $environment.config }}
          volumeMounts:
          {{- if $environment.config }}
          - mountPath: /etc/config
            readOnly: true
            name: config
          {{- end }}
          {{- if $environment.secret }}
          - mountPath: /etc/secret
            readOnly: true
            name: secret
          {{- end }}
      volumes:
      {{- $envName := $environment.name | default "prod" }}
      {{- /* */}}
      {{- if $environment.secret }}
      {{- $secretName := printf "%s--%s--%s" $envName $.Values.name $environment.secret.name }}
      - name: secret
        secret:
          secretName: {{ $secretName }}
          items:
          - key: {{ $environment.secret.name }} 
            path: {{ $environment.secret.name }}
      {{- end }}
      {{- /* */}}
      {{- if $environment.config }}
      {{- $configName := printf "%s--%s--%s" $envName $.Values.name $environment.config.name }}
      - name: config
        configMap:
          name: {{ $configName }}
          items:
            - key: {{ printf "%s.yaml" $environment.config.name }} 
              path: {{ printf "%s.yaml" $environment.config.name }} 
      {{- end }}
      {{- /* */}}
      {{- end }}
---
{{- end }}