{{- if not .Values.name }}
  {{ fail "You must provide a `service.name` in values.yaml" }}
{{- end }}
{{ $namespace := .Values.namespace | default "apps" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name | quote }}
    spec:
      containers:
        - name: {{ .Values.name | quote }}
          image: {{ printf "%s/%s:%s" .Values.repo .Values.name .Chart.version }}
          ports:
          - name: http
            containerPort: {{ .Values.port }}
          imagePullPolicy: IfNotPresent
          resources: 
            {{- if .Values.resources.requests }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            {{- end }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          {{- if .Values.env }}
          env:
          {{- range $key, $value := .Values.env}}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
