{{- range $k, $environment := .Values.environments }}
{{- /* Deploy production environment only when deployProduction override isn't set */}}
{{ $deployProduction := $.Values.overrides.deployProduction }}
{{- if or (not $environment.production) $deployProduction }}
{{- /* */}}
{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{- if and $environment.production (not $environment.name) }}
  {{ $name = $.Values.name }}
{{- end }}
{{- if and $.Values.overrides.environmentName }}
  {{ $name = printf "%s--%s" $.Values.overrides.environmentName $.Values.name }}
{{- end }}
{{- /* */}}
{{ $namespace := $.Values.global.stagingNamespace }}
{{- if $environment.production }}
  {{ $namespace = $.Values.global.prodNamespace }}
{{- end }}
{{- /* */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-canary" $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-stable" $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: http
---
{{- end }}
{{- end }}