{{ $cluster := .Values.cluster | default .Values.default.cluster }}
{{ $host := .Values.host | default .Values.default.host }}
{{ $gateway := .Values.gateway | default .Values.default.gateway }}
{{- /* */}}
{{- range $k, $environment := .Values.environments }}
{{- /* Deploy production environment only when deployProduction override isn't set */}}
{{ $deployProduction := $.Values.overrides.deployProduction }}
{{- if or (not $environment.production) $deployProduction }}
{{- /* */}}
{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{- if and $environment.production (not $environment.name) }}
  {{ $name = $.Values.name }}
{{- end }}
{{- if and $.Values.overrides.environmentName }}
  {{ $name = printf "%s-%s--%s" $.Values.overrides.environmentName ($environment.name | default "default") $.Values.name }}
{{- end }}
{{- /* */}}
{{ $namespace := $.Values.global.stagingNamespace }}
{{- if $environment.production }}
  {{ $namespace = $.Values.global.prodNamespace }}
{{- end }}
{{- /* */}}
{{ $svcHost := printf "%s-stable" $name }}
{{- /* */}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
spec:
{{- if not $environment.delegatedService }}
  hosts:
  - {{ $svcHost }}
  {{- /* */}}
  {{- $isPublic := $environment.public | default $.Values.default.public}}
  {{- if $isPublic }}
  - {{ printf "%s.%s.%s" $name $cluster $host }}
  {{- end }}
  {{- /* */}}
  {{- if $environment.customDomains }}
  {{- range $k, $domain := $environment.customDomains }}
  - {{ $domain }}
  {{- end }}
  {{- end }}
  {{- /* */}}
  gateways:
  - mesh
  - {{ "istio-system/public" }}
  - {{ "istio-system/public-com" }}
{{- end }}
  http:
  {{- if $environment.customRoute }}
{{ $environment.customRoute | toYaml | indent 2 }}
  {{- end }}
{{- $overrideHeaders := dict }}
{{- range $headerName, $headerValue := $.Values.overrides.matchHeaders }}
  {{- $_ := set $overrideHeaders $headerName (dict "exact" $headerValue) }}
{{- end }}
  - name: primary
{{- if $environment.customMatch }}
{{- range $k, $match := $environment.customMatch }}
  {{- $headers := get $match "headers" | default dict }}
  {{- $_ := mergeOverwrite $headers $overrideHeaders }}
  {{- if $headers }}
    {{- $_ := set $match "headers" $headers }}
  {{- end }}
  {{- if not $overrideHeaders }}
    {{- $_ := set $match "withoutHeaders" (dict "circuit-feature-environment" dict ) }}
  {{- end }}
{{- end }}
    match:
{{ $environment.customMatch | toYaml | indent 4 }}
{{- else if $overrideHeaders }}
    match:
{{- $matchHeaders := list (dict "headers" $overrideHeaders) }}
{{ $matchHeaders | toYaml | indent 4 }}
{{- end }}
    route:
    - destination:
        host: {{ printf "%s-stable" $name }}
        port:
          number: 80
      weight: 100
    - destination:
        host: {{ printf "%s-canary" $name }}
        port:
          number: 80
      weight: 0
    {{- if $.Values.mirror }}
    {{- if $.Values.mirror.enabled }}
    {{- if $environment.production }}
    mirror:
      host: {{ printf "%s--%s-stable" $.Values.mirror.environment $.Values.name }}
    mirrorPercentage:
      value: {{ $.Values.mirror.percentage }}
    {{- end }}
    {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}