{{ $namespace := .Release.Namespace | default "apps" }}
{{ $svcHost := printf "%s.%s.svc.cluster.local" .Chart.Name $namespace }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  hosts:
  - {{ $svcHost }}
  {{- if .Values.public }}
  - {{ printf "%s.%s.%s" .Chart.Name .Values.cluster .Values.host }}
  {{- end }}
  gateways:
  - mesh
  - {{ printf "istio-system/%s" .Values.gateway }}
  http:
  - route:
    - destination:
        host: {{ $svcHost }}
        port:
          number: 80