{{ $namespace := .Values.namespace | default "apps" }}
{{ $cluster := .Values.cluster | default .Values.default.cluster }}
{{ $host := .Values.host | default .Values.default.host }}
{{ $gateway := .Values.gateway | default .Values.default.gateway }}
{{- /* */}}
{{- range $k, $environment := .Values.environments }}
{{- /* */}}
{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{ if $environment.production }}
  {{ $name = $.Values.name }}
{{- end }}
{{- /* */}}
{{ $svcHost := printf "%s.%s.svc.cluster.local" $name $namespace }}
{{- /* */}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
spec:
  hosts:
  - {{ $svcHost }}
  {{- /* */}}
  {{- $isPublic := $environment.public | default $.Values.default.public}}
  {{- if $isPublic }}
  - {{ printf "%s.%s.%s" $name $cluster $host }}
  {{- end }}
  {{- /* */}}
  {{- if $environment.customDomain }}
  - {{ $environment.customDomain }}
  {{- end }}
  {{- /* */}}
  gateways:
  - mesh
  - {{ printf "istio-system/%s" $gateway }}
  http:
  - route:
    - destination:
        host: {{ $svcHost }}
        port:
          number: 80
---
{{- end }}