{{ $namespace := .Values.namespace | default "apps" }}
{{ $cluster := .Values.cluster | default .Values.default.cluster }}
{{ $host := .Values.host | default .Values.default.host }}
{{ $gateway := .Values.gateway | default .Values.default.gateway }}
{{- /* */}}
{{- range $k, $environment := .Values.environments }}
{{- /* */}}
{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{ if $environment.production }}
  {{ $name = $.Values.name }}
{{- end }}
{{- /* */}}
{{ $svcHost := printf "%s-stable" $name }}
{{- /* */}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
spec:
{{- if not $environment.delegatedService }}
  hosts:
  - {{ $svcHost }}
  {{- /* */}}
  {{- $isPublic := $environment.public | default $.Values.default.public}}
  {{- if $isPublic }}
  - {{ printf "%s.%s.%s" $name $cluster $host }}
  {{- end }}
  {{- /* */}}
  {{- if $environment.customDomain }}
  - {{ $environment.customDomain }}
  {{- end }}
  {{- /* */}}
  gateways:
  - mesh
  - {{ "istio-system/public" }}
  - {{ "istio-system/public-com" }}
{{- end }}
  http:
  {{- if $environment.customRoute }}
{{ $environment.customRoute | toYaml | indent 2}}
  {{- end }}
  - name: primary
    route:
    - destination:
        host: {{ printf "%s-stable" $name }}
        port:
          number: 80
      weight: 100
    - destination:
        host: {{ printf "%s-canary" $name }}
        port:
          number: 80
      weight: 0
    {{- if $.Values.mirror }}
    {{- if $.Values.mirror.enabled }}
    {{- if $environment.production }}
    mirror:
      host: {{ printf "%s--%s-stable" $.Values.mirror.environment $.Values.name }}
    mirrorPercentage:
      value: {{ $.Values.mirror.percentage }}
    {{- end }}
    {{- end }}
    {{- end }}
---
{{- end }}