{{- range $k, $environment := .Values.environments }}
{{- /* Deploy production environment only when deployProduction override isn't set */}}
{{ $deployProduction := $.Values.overrides.deployProduction }}
{{- if or (not $environment.production) $deployProduction }}
{{- /* */}}
{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{- if and $environment.production (not $environment.name) }}
  {{ $name = $.Values.name }}
{{- end }}
{{- if and $.Values.overrides.environmentName }}
  {{ $name = printf "%s-%s--%s" $.Values.overrides.environmentName ($environment.name | default "default") $.Values.name }}
{{- end }}
{{- /* */}}
{{ $namespace := $.Values.global.stagingNamespace }}
{{- if $environment.production }}
  {{ $namespace = $.Values.global.prodNamespace }}
{{- end }}
{{- /* */}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ $name }}
  minReplicas: {{ $environment.minReplicas | default $.Values.default.min }}
  maxReplicas: {{ $environment.maxReplicas | default $.Values.default.max }}
  targetCPUUtilizationPercentage: {{ $environment.targetCPU | default $.Values.default.target }}
---
{{- end }}
{{- end }}