{{- if .Values.metrics.enabled }}
{{ $namespace := .Release.Namespace | default "apps" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ $namespace }}
spec:
  endpoints:
    - interval: {{ .Values.metrics.interval | default "15s" }}
      port: http
  namespaceSelector:
    matchNames:
      - {{ $namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}
