{{- range $k, $environment := .Values.environments }}
{{- /* Deploy production environment only when deployProduction override isn't set */}}
{{ $deployProduction := $.Values.overrides.deployProduction }}
{{- if or (not $environment.production) $deployProduction }}
{{- /* */}}
{{- if $environment.metrics }}
{{- if $environment.metrics.enabled }}
{{- /* */}}
{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{- if and $environment.production (not $environment.name) }}
  {{ $name = $.Values.name }}
{{- end }}
{{- if and $.Values.overrides.environmentName }}
  {{ $name = printf "%s-%s--%s" $.Values.overrides.environmentName ($environment.name | default "default") $.Values.name }}
{{- end }}
{{- /* */}}
{{ $namespace := $.Values.global.stagingNamespace }}
{{- if $environment.production }}
  {{ $namespace = $.Values.global.prodNamespace }}
{{- end }}
{{- /* */}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ $name }}
    circuit/service-name: {{ $.Values.name }}
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  endpoints:
    - interval: {{ $environment.metrics.interval | default $.Values.default.metricsInterval }}
      port: http
      {{- if $environment.metrics.path }}
      path: {{ $environment.metrics.path }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
