{{ $namespace := .Values.namespace | default "apps" }}
{{- /* */}}
{{- range $k, $environment := .Values.environments }}
{{- if $environment.secret }}
{{- /* */}}
{{- if not $environment.secret.name }}
  {{ fail "secret name is required when using secret"}}
{{- end }}
{{- /* */}}
{{ $envName := $environment.name | default "prod" }}
{{ $secretName := printf "%s--%s--%s" $envName $.Values.name $environment.secret.name }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ $.Values.default.projectId | quote }}
  data:
    - key: {{ $environment.secret.name }}
      name: {{ $environment.secret.name }}
      version: {{ $environment.secret.version | default "1" }} 
---
{{- /* */}}
{{- end }}
{{- end }}