{{- range $k, $environment := .Values.environments }}
{{- /* Deploy production environment only when deployProduction override isn't set */}}
{{ $deployProduction := $.Values.overrides.deployProduction }}
{{- if or (not $environment.production) $deployProduction }}

{{ $secretName := printf "%s--%s" $environment.name $.Values.name }}
{{- if and $environment.production (not $environment.name) }}
  {{ $secretName = $.Values.name }}
{{- end }}
{{- if and $.Values.overrides.environmentName }}
  {{ $secretName = printf "%s--%s" $.Values.overrides.environmentName $.Values.name }}
{{- end }}

{{ $namespace := $.Values.global.stagingNamespace }}
{{- if $environment.production }}
  {{ $namespace = $.Values.global.prodNamespace }}
{{- end }}

{{ $shouldRender := false }}
{{- range $key, $value := $environment.env}}
  {{- if kindIs "map" $value}}
    {{ $shouldRender = true }}
  {{end}}
{{end}}
{{- if $environment.volumes }}
{{- if $environment.volumes.secrets }}
  {{- range $j, $value := $environment.volumes.secrets }}
    {{- if kindIs "map" $value.fromRemote }}
      {{ $shouldRender = true }}
    {{end}}
  {{end}}
{{end}}
{{end}}

{{- if $shouldRender }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcpsm-secret-store
  target: {}
  data:
  {{- range $key, $value := $environment.env}}
    {{- if kindIs "map" $value}}
    {{- $secret := $value.fromSecret }}
  - secretKey: {{ include "secrets.key.env" (dict "key" $key "secret" $secret) }}
    remoteRef: 
      key: {{ $secret.name | quote }}
      version: {{ $secret.version | quote }}
    {{- end}}
  {{- end }}

  {{- if $environment.volumes }}
  {{- if $environment.volumes.secrets }}
  {{- range $j, $value := $environment.volumes.secrets }}
    {{- if kindIs "map" $value.fromRemote }}
    {{- $secret := $value.fromRemote }}
  - secretKey: {{ include "secrets.key.mount" (dict "key" $value.name "secret" $secret) }}
    remoteRef: 
      key: {{ $secret.name | quote }}
      version: {{ $secret.version | quote }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
