{{ $namespace := .Values.namespace | default "apps" }}
{{- /* */}}
{{- range $k, $environment := .Values.environments }}
{{- if $environment.secret }}
{{- /* */}}
{{- if not $environment.secret.name }}
  {{ fail "secret name is required when using secret"}}
{{- end }}
{{- /* */}}
{{ $envName := $environment.name | default "prod" }}
{{ $secretName := printf "%s--%s--%s" $envName $.Values.name $environment.secret.name }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-gcpsm-secret-store
  data:
  - secretKey: {{ $environment.secret.name }}
    remoteRef:
      key: {{ $environment.secret.name }}
      version: {{ $environment.secret.version | default "1" | quote }} 
---
{{- /* */}}
{{- end }}
{{- end }}
