{{- range $k, $environment := .Values.environments }}
{{- /* Deploy production environment only when deployProduction override isn't set */}}
{{ $deployProduction := $.Values.overrides.deployProduction }}
{{- if or (not $environment.production) $deployProduction }}

{{- if $environment.auth }}

{{- if not $environment.auth.issuers }}
{{ fail "You must provide the issuers when enabling auth" }}
{{- end }}

{{ $name := printf "%s--%s" $environment.name $.Values.name }}
{{- if and $environment.production (not $environment.name) }}
  {{ $name = $.Values.name }}
{{- end }}
{{- if and $.Values.overrides.environmentName }}
  {{ $name = printf "%s-%s--%s" $.Values.overrides.environmentName ($environment.name | default "default") $.Values.name }}
{{- end }}

{{ $namespace := $.Values.global.stagingNamespace }}
{{- if $environment.production }}
  {{ $namespace = $.Values.global.prodNamespace }}
{{- end }}

apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  jwtRules:
  {{- range $issuer := $environment.auth.issuers }}
  {{- if not $issuer.iss }}
  {{ fail "You must provide the iss for each issuer" }}
  {{- end }}

  {{- if not $issuer.jwksUri }}
  {{ fail "You must provide the jwksUri for each issuer" }}
  {{- end }}
  - issuer: {{ $issuer.iss }}
    jwksUri: {{ $issuer.jwksUri }}
    forwardOriginalToken: true
  {{- end }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  action: ALLOW
  rules:
  {{- if $environment.auth.allowPaths }}
  - to:
    - operation:
        paths:
        {{- range $path := $environment.auth.allowPaths }}
        - {{ $path }}
        {{- end }}
  {{- end }}
  - to:
    - operation:
        methods: ['OPTIONS']
  - when:
    - key: request.auth.claims[iss]
      values:
      {{- range $issuer := $environment.auth.issuers }}
      - {{ $issuer.iss }}
      {{- end }}
---
{{- end }}

{{- end }}
{{- end }}
