name: Test

on:
  pull_request: {}

jobs:
  service-template:
    name: Template the service chart with minimal values
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Helm
        run: snap install helm --classic
      - name: Template service chart
        run: cd charts/service && helm template test ./ -f values-test.yaml